<Project Sdk="Microsoft.NET.Sdk.Web">

	<ItemGroup>
		<ProjectReference Include="..\SmartXOne.Shared\SmartXOne.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="data\" />
	</ItemGroup>

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

</Project>



